// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srvthnemnmvpjntimgqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydnRobmVtbm12cGpudGltZ3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjUyNjgsImV4cCI6MjA2MDUwMTI2OH0.SM4t545UtyRFwOii-YrqBhkxzG-REIIvze8DpYUXMWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);